/**
 * Thermal Dawn: website lead capture, Gmail to leads.csv
 * ------------------------------------------------------
 * Reads website form notifications out of Gmail and appends one row per
 * submission to Sales +/CRM/leads.csv. Triage happens there, by a person;
 * this script only captures.
 *
 * Why Apps Script: the notification emails hold customer PII, and running
 * inside the same Workspace keeps that PII inside it. No third party sees it.
 *
 * The parser lives in lead-parser.gs, in the same Apps Script project. It is
 * kept separate because scripts/test-lead-parser.js runs it under Node against
 * emails generated by api/lead.js itself. Apps Script files share one global
 * scope, so parseLead() is simply available here.
 *
 * Setup: SETUP.md, next to this file.
 */

// ---------------------------------------------------------------- config ---

var CFG = {
  // The folder holding leads.csv. Get the id from the folder's URL:
  // drive.google.com/drive/folders/THIS_PART
  FOLDER_ID: 'PASTE_THE_CRM_FOLDER_ID_HERE',
  FILE_NAME: 'leads.csv',

  // Gmail search. Sender is the notification address for both streams.
  // -label: keeps processed mail out of the next run.
  QUERY: 'from:nickz@thermaldawn.com ' +
         'subject:("New website lead" OR "New website message" OR ' +
         '"New subscriber" OR "New deposit intent") ' +
         '-label:' + 'crm-captured',

  CAPTURED_LABEL: 'crm-captured',   // applied after a successful write
  ERROR_LABEL: 'crm-capture-error', // applied when a message will not parse

  MAX_PER_RUN: 50,                  // keeps a backlog run inside the time limit
  TIMEZONE: 'Australia/Sydney'
};

// ------------------------------------------------------------------ main ---

function captureLeads() {
  // Two triggers can overlap on a slow run. Without this both read the file,
  // both append, and the second write wins: one lead silently lost.
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(30000)) {
    Logger.log('Another run holds the lock; exiting.');
    return;
  }

  try {
    var captured = getOrCreateLabel_(CFG.CAPTURED_LABEL);
    var errored  = getOrCreateLabel_(CFG.ERROR_LABEL);
    var file     = getLeadsFile_();

    var existingIds = readMessageIds_(file);
    var threads = GmailApp.search(CFG.QUERY, 0, CFG.MAX_PER_RUN);
    Logger.log('Threads matched: ' + threads.length);

    var rows = [], done = 0, skipped = 0, failed = 0;

    threads.forEach(function (thread) {
      // Iterate MESSAGES, not threads. Two submissions from one address get
      // threaded by Gmail (identical subject, same sender), and a thread-level
      // label would hide the second one forever.
      thread.getMessages().forEach(function (msg) {
        var id = msg.getId();
        if (existingIds[id]) { skipped++; return; }

        var subject = msg.getSubject() || '';
        // A reply quotes the whole form body, from the same sender the query
        // matches, so it parses as a fresh lead carrying the CUSTOMER's
        // address. Confirmed on a real thread. Exclude replies and forwards.
        if (/^\s*(re|fwd|fw)\s*:/i.test(subject)) { skipped++; return; }

        var body = msg.getPlainBody() || '';
        if (/^\s*(On .* wrote:|>)/m.test(body) && !/Form\s*:/.test(body)) {
          skipped++; return;
        }

        try {
          var d = parseLead(body);
          if (!d['Email']) throw new Error('no Email field found');
          if (isTest_(d['Email'])) { skipped++; captured.addToThread(thread); return; }

          rows.push(buildRow_(d, msg));
          existingIds[id] = true;
          done++;
        } catch (err) {
          Logger.log('PARSE FAILED ' + id + ': ' + err.message);
          errored.addToThread(thread);
          failed++;
        }
      });
    });

    if (rows.length) appendRows_(file, rows);

    // Label only AFTER the write succeeds. Labelling first means a failed
    // write is never retried, and the lead is gone.
    threads.forEach(function (t) {
      var anyErrored = t.getLabels().some(function (l) {
        return l.getName() === CFG.ERROR_LABEL;
      });
      if (!anyErrored) captured.addToThread(t);
    });

    writeHeartbeat_(done, skipped, failed);
    Logger.log('Captured ' + done + ', skipped ' + skipped + ', failed ' + failed);
  } finally {
    lock.releaseLock();
  }
}

// ----------------------------------------------------------------- parts ---

function isTest_(email) {
  var e = String(email).toLowerCase();
  return /^(qa-|deploy-check|test@|noreply)/.test(e) ||
         /@example\.(com|org)$/.test(e);
}

function getOrCreateLabel_(name) {
  // GmailApp addresses labels by NAME. A Gmail API label id (Label_1234...)
  // will not work here and returns null.
  return GmailApp.getUserLabelByName(name) || GmailApp.createLabel(name);
}

function getLeadsFile_() {
  var folder = DriveApp.getFolderById(CFG.FOLDER_ID);
  var it = folder.getFilesByName(CFG.FILE_NAME);
  if (it.hasNext()) return it.next();
  throw new Error('leads.csv not found in the configured folder. Create it ' +
                  'with its header row before running this.');
}

/* Reads column 4, gmail_message_id, out of every row. This is the dedupe key,
   so a wrong answer here either duplicates a lead or drops one. Quoted commas
   in an earlier column would break a plain split(','), and comments are free
   text, so parse the row properly rather than assuming. */
function csvRow_(line) {
  var out = [], cur = '', q = false;
  for (var i = 0; i < line.length; i++) {
    var c = line.charAt(i);
    if (q) {
      if (c === '"') {
        if (line.charAt(i + 1) === '"') { cur += '"'; i++; }
        else q = false;
      } else cur += c;
    } else if (c === '"') q = true;
    else if (c === ',') { out.push(cur); cur = ''; }
    else cur += c;
  }
  out.push(cur);
  return out;
}

function readMessageIds_(file) {
  var seen = {};
  var text = file.getBlob().getDataAsString();
  text.split(/\r?\n/).forEach(function (line, i) {
    if (!i || !line) return;
    var id = csvRow_(line)[3];
    if (id) seen[id] = true;
  });
  return seen;
}

function csvCell_(v) {
  v = (v === undefined || v === null) ? '' : String(v);
  v = v.replace(/\r?\n/g, ' ').trim();
  return '"' + v.replace(/"/g, '""') + '"';
}

function buildRow_(d, msg) {
  var now = Utilities.formatDate(new Date(), CFG.TIMEZONE, "yyyy-MM-dd'T'HH:mm:ssXXX");
  // The message's own date is unambiguous. The "Submission Time" string says
  // AEST even when Sydney is on AEDT, so parsing it would be wrong half the
  // year; it is kept verbatim in the CSV only as a human cross-check.
  var submitted = Utilities.formatDate(msg.getDate(), CFG.TIMEZONE, "yyyy-MM-dd'T'HH:mm:ssXXX");
  var body = msg.getPlainBody() || '';
  var site = /thermaldawn\.com\/so\/tr|wix/i.test(body) ? 'wix' : 'freevolt';

  var name = d['Name'] || '';
  var first = d['First name'] || (name ? name.split(' ')[0] : '');
  var last  = d['Last name']  || (name ? name.split(' ').slice(1).join(' ') : '');

  return [
    Utilities.getUuid().slice(0, 8),      // lead_id
    now,                                   // captured_at
    submitted,                             // submitted_at
    msg.getId(),                           // gmail_message_id
    d['Form'] || '',                       // form
    site,                                  // source_site
    first, last,
    String(d['Email'] || '').toLowerCase(),
    d['Phone'] || '',
    d['Suburb'] || '',
    d['State'] || '',
    d['Solar'] || '',
    d['Battery'] || '',
    d['Current heating/cooling system'] || '',
    d["What's driving interest"] || '',
    d['Timeline'] || '',
    d['Comments'] || '',
    d['Newsletter opt-in'] || '',
    'New',                                 // triage_status
    '', '', '', '', '', '', ''             // agent columns, filled on triage
  ].map(csvCell_).join(',');
}

function appendRows_(file, rows) {
  var text = file.getBlob().getDataAsString();
  if (text.length && !/\n$/.test(text)) text += '\n';
  file.setContent(text + rows.join('\n') + '\n');
}

function writeHeartbeat_(done, skipped, failed) {
  // Without this, a script that stops running looks exactly like a week with
  // no leads. That ambiguity is what hid the August capture gap for 3 weeks.
  PropertiesService.getScriptProperties().setProperties({
    last_run_at: new Date().toISOString(),
    last_run_captured: String(done),
    last_run_skipped: String(skipped),
    last_run_failed: String(failed)
  });
}

/** Run this once by hand to confirm the config before setting the trigger. */
function testConfig() {
  var folder = DriveApp.getFolderById(CFG.FOLDER_ID);
  Logger.log('Folder OK: ' + folder.getName());
  Logger.log('leads.csv OK: ' + getLeadsFile_().getName());
  Logger.log('Parser loaded: ' + (typeof parseLead === 'function'));
  Logger.log('Threads matching query: ' + GmailApp.search(CFG.QUERY, 0, 5).length);
  Logger.log('Existing rows: ' + Object.keys(readMessageIds_(getLeadsFile_())).length);
}

/** Read the heartbeat. Run by hand any time to see if capture is alive. */
function showHeartbeat() {
  Logger.log(JSON.stringify(
    PropertiesService.getScriptProperties().getProperties(), null, 2));
}

/* Apps Script ignores this; Node uses it so the CSV round-trip is testable.
   See scripts/test-lead-parser.js. */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { csvCell_: csvCell_, csvRow_: csvRow_, isTest_: isTest_ };
}
