/* Extracts every page's customer-facing copy into one reviewable file.

     npm run copy:dump

   Why: copy lives inside 28 hand-written HTML files and only ~38% of those
   bytes are words. A review session that reads the raw pages spends most of
   its context on markup. This writes a single file of just the copy, with a
   `path:line` on every block so any finding maps straight back to the edit.

   Output goes to .claude/copy-dump.txt, which is gitignored and excluded from
   the deploy. Do NOT write it to the repo root: this is a static site served
   from the root, so a file there is publicly fetchable.

   This prints only a summary. Read the output file for the copy itself. */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, ".claude", "copy-dump.txt");

/* Generated or non-copy trees. assets/animations is generated by
   build-homepage-anim.js, so its strings are reviewed at the source, not here. */
const SKIP_DIRS = new Set(["node_modules", ".git", ".claude", "tools", "scripts"]);
const SKIP_PATHS = [path.join("assets", "animations")];

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".") && entry.name !== ".claude") continue;
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.relative(ROOT, full);
    if (SKIP_PATHS.some((p) => rel.startsWith(p))) continue;
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith(".html")) out.push(full);
  }
  return out;
}

const ENTITIES = {
  amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ",
  mdash: "—", ndash: "–", hellip: "...", times: "×",
  harr: "<->", rarr: "->", larr: "<-", deg: "°", sup2: "²",
  copy: "©", reg: "®", trade: "™", middot: "·",
};

function decode(s) {
  return s
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&([a-z][a-z0-9]*);/gi, (m, name) => {
      const k = name.toLowerCase();
      return Object.prototype.hasOwnProperty.call(ENTITIES, k) ? ENTITIES[k] : m;
    });
}

const stripTags = (s) => s.replace(/<[^>]*>/g, " ");
/* Inline tags (<strong>, <a>) become spaces, which strands punctuation:
   "$40,000 ." and "thermal store : an". Pull it back after collapsing. */
const tidy = (s) =>
  decode(stripTags(s))
    .replace(/\s+/g, " ")
    .replace(/\s+([,.;:!?%])/g, "$1")
    /* A live-stat span sits right after its symbol ("$<span>1,439</span>"),
       so stripping tags leaves "$ 1,439" and a reviewer reports a spacing
       bug that is not in the HTML (happened 22 Aug). Pull those back too. */
    .replace(/([$~])\s+(?=[\d.])/g, "$1")
    .replace(/\(\s+/g, "(")
    .replace(/\s+\)/g, ")")
    .trim();
const hasWords = (s) => /[a-z]{2}/i.test(s);

/* The quote char has to be captured and back-referenced: several descriptions
   are double-quoted but contain an apostrophe, and a [^"']* class truncates
   them at "customer's". */
function attr(html, re) {
  const m = html.match(re);
  if (!m) return null;
  return decode(m[m.length - 1]).trim();
}

const CURLY = /[‘’“”]/;

const files = walk(ROOT).sort();
const pages = [];
let emDashLines = [];
let draftLines = [];
let curlyLines = [];
let enDashLines = [];

for (const file of files) {
  const rel = path.relative(ROOT, file).replace(/\\/g, "/");
  const src = fs.readFileSync(file, "utf8");
  const lines = src.split(/\r?\n/);

  const page = {
    rel,
    title: attr(src, /<title>([^<]*)<\/title>/i),
    description: attr(src, /<meta\s+name=(["'])description\1\s+content=(["'])([\s\S]*?)\2/i),
    ogTitle: attr(src, /<meta\s+property=(["'])og:title\1\s+content=(["'])([\s\S]*?)\2/i),
    blocks: [],
    chartLabels: [],
  };

  let inBody = false;
  let skipUntil = null; // closing tag we're waiting for (script/style)
  let svgDepth = 0;

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const n = i + 1;

    if (!inBody) {
      if (/<body[\s>]/i.test(raw)) inBody = true;
      continue;
    }
    if (/<\/body>/i.test(raw)) break;

    if (skipUntil) {
      if (new RegExp(`</${skipUntil}`, "i").test(raw)) skipUntil = null;
      continue;
    }
    const opens = raw.match(/<(script|style)[\s>]/i);
    if (opens && !new RegExp(`</${opens[1]}`, "i").test(raw)) {
      skipUntil = opens[1].toLowerCase();
      continue;
    }

    /* SVG: the tags are markup but <text> holds real chart labels, and the
       draft figures live in them. Collect those separately. */
    const svgOpen = (raw.match(/<svg[\s>]/gi) || []).length;
    const svgClose = (raw.match(/<\/svg>/gi) || []).length;
    if (svgDepth > 0 || svgOpen > 0) {
      const texts = raw.match(/<text[^>]*>([^<]*)<\/text>/gi) || [];
      for (const t of texts) {
        const v = tidy(t);
        if (v) page.chartLabels.push({ n, text: v });
      }
      svgDepth += svgOpen - svgClose;
      if (svgDepth < 0) svgDepth = 0;
      if (svgOpen > 0 || svgDepth > 0) continue;
    }

    const text = tidy(raw);
    if (!text) continue;

    /* The mechanical checks run BEFORE the hasWords gate. A bare range like
       "$20,000-$40,000" (written with an entity) decodes to a dash with no
       two consecutive letters in it, so hasWords dropped the line and the
       counters read zero while six were live on the site. Sal found those
       by eye on 21 Aug; this is why the tool could not. */
    const mech = [];
    if (text.includes("—")) { mech.push("EM-DASH"); emDashLines.push(`${rel}:${n}`); }
    if (CURLY.test(text)) { mech.push("CURLY-QUOTE"); curlyLines.push(`${rel}:${n}`); }
    /* House style writes ranges as "to". */
    if (text.includes("–")) { mech.push("EN-DASH"); enDashLines.push(`${rel}:${n}`); }

    if (!hasWords(text)) continue;

    const flags = mech.slice();
    if (/class="[^"]*\bdraft\b/.test(raw)) { flags.push("DRAFT"); draftLines.push(`${rel}:${n}`); }
    if (/<button|class="btn\b|class="[^"]*\bbtn\b/.test(raw)) flags.push("CTA");

    page.blocks.push({ n, text, flags });
  }

  pages.push(page);
}

/* ---------- write the dump ---------- */
const out = [];
out.push("THERMAL DAWN, SITE COPY DUMP");
out.push("Generated by npm run copy:dump. Do not edit this file; edit the pages.");
out.push("Every block is prefixed with the file and line it came from.");
out.push("Flags: [DRAFT] figure awaiting sign-off, [CTA] button label,");
out.push("       [EM-DASH] banned punctuation, [EN-DASH] range that should read \"to\",");
out.push("       [CURLY-QUOTE] smart quote where the site uses straight.");
out.push("");
out.push(`${pages.length} pages.`);
out.push("=".repeat(78));

for (const p of pages) {
  out.push("");
  out.push(`## ${p.rel}`);
  if (p.title) out.push(`   <title>       ${p.title}`);
  if (p.ogTitle && p.ogTitle !== p.title) out.push(`   og:title      ${p.ogTitle}`);
  if (p.description) out.push(`   description   ${p.description}`);
  out.push("");
  for (const b of p.blocks) {
    const flag = b.flags.length ? ` [${b.flags.join("][")}]` : "";
    out.push(`${String(b.n).padStart(4)}:${flag} ${b.text}`);
  }
  if (p.chartLabels.length) {
    out.push("");
    out.push("   -- chart labels (inside SVG) --");
    for (const c of p.chartLabels) out.push(`${String(c.n).padStart(4)}:  ${c.text}`);
  }
}

out.push("");
out.push("=".repeat(78));
out.push("MECHANICAL FLAGS");
out.push(`em dashes (banned sitewide): ${emDashLines.length}${emDashLines.length ? " -> " + emDashLines.join(", ") : ""}`);
out.push(`draft figures awaiting sign-off: ${draftLines.length}${draftLines.length ? " -> " + draftLines.join(", ") : ""}`);
out.push(`curly quotes (site uses straight): ${curlyLines.length}${curlyLines.length ? " -> " + curlyLines.join(", ") : ""}`);
out.push(`en dashes (ranges should read "to"): ${enDashLines.length}${enDashLines.length ? " -> " + enDashLines.join(", ") : ""}`);

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out.join("\n") + "\n", "utf8");

const words = pages.reduce((a, p) => a + p.blocks.reduce((b, x) => b + x.text.split(/\s+/).length, 0), 0);
const bytes = fs.statSync(OUT).size;
console.log(`Wrote ${path.relative(ROOT, OUT).replace(/\\/g, "/")}`);
console.log(`  ${pages.length} pages, ${words.toLocaleString()} words, ${(bytes / 1024).toFixed(0)} KB (~${Math.round(bytes / 4).toLocaleString()} tokens)`);
console.log(`  em dashes: ${emDashLines.length}, en dashes: ${enDashLines.length}, draft figures: ${draftLines.length}, curly quotes: ${curlyLines.length}`);
console.log(`Read that file to review the copy. Report findings as path:line.`);

/* ---------- copy that lives inside embedded interactives ------------------
   The diagrams under assets/animations are iframed, so their strings never
   appear in a page's own HTML and a reviewer reading the pack cannot see
   them. They are still customer-facing copy: the component names, the
   captions under them, and a paragraph of explanation for each one. Pull
   them out and hang them off whichever page embeds the file.

   Generated animations stay excluded, per the note on SKIP_PATHS: their
   strings are reviewed in the builder that emits them, not here. */
const ANIM_DIR = path.join(ROOT, "assets", "animations");

function readInteractive(relSrc) {
  const file = path.join(ROOT, relSrc.replace(/^\//, "").split("?")[0]);
  if (!file.startsWith(ANIM_DIR) || !fs.existsSync(file)) return null;
  const raw = fs.readFileSync(file, "utf8");
  if (/GENERATED FILE/i.test(raw)) return null;

  const lineOf = (idx) => raw.slice(0, idx).split("\n").length;
  const out = [];
  const seen = new Set();
  const add = (label, text, idx) => {
    const t = tidy(decode(String(text)));
    if (!t || !hasWords(t) || seen.has(t)) return;
    seen.add(t);
    out.push({ label, text: t, n: lineOf(idx) });
  };

  /* static chrome: the heading, the toggle buttons, the standing note */
  const bodyAt = raw.indexOf("<body");
  if (bodyAt !== -1) {
    const scriptAt = raw.indexOf("<script", bodyAt);
    const tail = raw.slice(bodyAt, scriptAt === -1 ? undefined : scriptAt);
    const re = />([^<>{}]{2,})</g;
    let m;
    while ((m = re.exec(tail))) add("chrome", m[1], bodyAt + m.index);
  }

  /* the component data: label / sub / info on each object literal */
  const KEYS = { label: "name", sub: "caption", info: "detail" };
  for (const key of Object.keys(KEYS)) {
    const re = new RegExp(key + ':\\s*"((?:[^"\\\\]|\\\\.)*)"', "g");
    let m;
    while ((m = re.exec(raw))) add(KEYS[key], m[1].replace(/\\"/g, '"'), m.index);
  }

  /* Prose that sits behind no key at all. intelligence-day.html keeps its
     eight phase narrations in plain arrays, so the key rule above saw none
     of them and the pack quietly under-reported the best copy on the page
     (found 22 Aug). Anything that reads as a sentence is customer copy,
     wherever it lives; code-shaped strings are filtered out. */
  const CODEISH = /[<>{}]|rgba?\(|translate\(|scale\(|url\(|\d+px|#[0-9a-f]{3,8}\b|^[.#]/i;
  const proseRe = /"((?:[^"\\]|\\.){15,}?)"/g;
  let pm;
  while ((pm = proseRe.exec(raw))) {
    const v = pm[1].replace(/\\"/g, '"');
    if (CODEISH.test(v)) continue;
    if (!/[.!?]$/.test(v)) continue;       /* a sentence, not an identifier */
    if (!/[a-z]\s+[a-z]/i.test(v)) continue; /* at least two words */
    add("narration", v, pm.index);
  }
  return out.length
    ? { rel: path.relative(ROOT, file).split(path.sep).join("/"), items: out }
    : null;
}

/* map each page to the interactives it embeds */
for (const p of pages) {
  p.interactives = [];
  const src = fs.readFileSync(path.join(ROOT, p.rel), "utf8");
  const re = /<iframe[^>]*\ssrc="([^"]+)"/g;
  let m;
  while ((m = re.exec(src))) {
    const got = readInteractive(m[1]);
    if (got) p.interactives.push(got);
  }
}

/* ---------- the reviewer pack: organised markdown, one file per page ------
   The txt dump above is tuned for one AI session reading everything at once.
   The pack is for HUMAN reviewers working a page at a time: same content,
   same path:line references, split per page with an INDEX.md carrying the
   review brief. Lives in .claude/ (gitignored, never deployed) because the
   repo root is served as the site. */
const PACK = path.join(ROOT, ".claude", "copy-review");
const PAGES_DIR = path.join(PACK, "pages");
fs.rmSync(PACK, { recursive: true, force: true });
fs.mkdirSync(PAGES_DIR, { recursive: true });

const slug = (rel) => rel.replace(/\/index\.html$/, "").replace(/\.html$/, "").replace(/[\/]/g, "--") || "home";
const SECTIONS = [
  ["Home", (r) => r === "index.html"],
  ["Hydronic", (r) => r.startsWith("hydronic/")],
  ["Pre-order and checkout", (r) => r.startsWith("pre-order/") || r.startsWith("thank-you/")],
  ["Company", (r) => ["mission/index.html", "intelligence/index.html", "contact/index.html"].includes(r)],
  ["Blog", (r) => r.startsWith("blog/")],
  ["System pages", () => true],
];

for (const p of pages) {
  const md = [];
  md.push(`# ${p.title || p.rel}`);
  md.push("");
  md.push(`**File:** \`${p.rel}\` · generated by \`npm run copy:dump\`, do not edit here.`);
  md.push("");
  md.push("| | |");
  md.push("|---|---|");
  if (p.title) md.push(`| \`<title>\` | ${p.title} |`);
  if (p.ogTitle && p.ogTitle !== p.title) md.push(`| og:title | ${p.ogTitle} |`);
  if (p.description) md.push(`| meta description | ${p.description} |`);
  md.push("");
  md.push("## Copy");
  md.push("");
  for (const b of p.blocks) {
    const flag = b.flags.length ? ` **[${b.flags.join("][")}]**` : "";
    md.push(`- \`${p.rel}:${b.n}\`${flag} ${b.text}`);
  }
  if (p.chartLabels.length) {
    md.push("");
    md.push("## Chart labels (inside SVG)");
    md.push("");
    for (const c of p.chartLabels) md.push(`- \`${p.rel}:${c.n}\` ${c.text}`);
  }
  for (const iv of p.interactives || []) {
    md.push("");
    md.push(`## Embedded interactive: \`${iv.rel}\``);
    md.push("");
    md.push("Copy inside the diagram. It is iframed, so it never appears in this page's own HTML, but readers see it on the page.");
    md.push("");
    md.push("_Extracted from the source: static markup, the component `label`/`sub`/`info` fields, and any string that reads as a sentence. Short UI labels held in JS variables can still slip through, so check the file itself before concluding something is missing._");
    md.push("");
    for (const it of iv.items) md.push(`- \`${iv.rel}:${it.n}\` *(${it.label})* ${it.text}`);
  }
  fs.writeFileSync(path.join(PAGES_DIR, slug(p.rel) + ".md"), md.join("\n") + "\n", "utf8");
}

const now = new Date().toISOString().slice(0, 10);
/* Review round folder, e.g. feedback/2026-08-21-copy-review/ */
const REVIEW_ROUND = now + "-copy-review";
const idx = [];
idx.push("# Thermal Dawn site copy, review pack");
idx.push("");
idx.push(`Generated ${now} by \`npm run copy:dump\`. Regenerate rather than edit: every file here is derived from the HTML, and \`path:line\` in each entry is where the real copy lives.`);
idx.push("");
/* Feedback lands in a dated folder per review round, not loose in the repo root. */
idx.push("## How to review");
idx.push("");
idx.push("- Report findings as `path:line`, current text, proposed replacement. Do not edit pages directly; Nick applies or delegates the edits.");
idx.push("- **Save your review to `feedback/" + REVIEW_ROUND + "/` in the repo**, as one markdown file named for you, for example `COPY-FEEDBACK-yourname.md`. That folder is the record of who said what; do not overwrite anyone else's file.");
idx.push("- Read across pages, not one at a time, when checking claims: the bugs that matter are one page contradicting another.");
idx.push("- `pre-order/terms/` is legal copy, verbatim from Nick. Flag, never reword.");
idx.push("- Measured figures (savings counters, evening-carry stats) come from platform telemetry. If one looks wrong, query it; never substitute a plausible number.");
idx.push("");
idx.push("## Standing rules the copy must hold to");
idx.push("");
idx.push("- No rebates, subsidies or VEU anywhere. Mentioning future money delays orders.");
idx.push("- No counting installs (no \"first\", \"second\", \"two homes live\"). Name the place, state the fact. The pricing page's early-adopter framing is the deliberate exception.");
idx.push("- Origin claims scope to the store, controls and technology, never the whole system. The heat pump is sourced, not built.");
idx.push("- The peak window is 5pm to 9pm, measured. Never 3pm or 4pm variants.");
idx.push("- 70C flow temperature is a spec commitment, not a measurement. Do not rewrite it as measured.");
idx.push("- The thermal store holds **30 kWh** (Nick, 21 Aug). Earlier 35 and 60 kWh figures are both superseded.");
idx.push("- No warranty duration is stated anywhere, and a ten-year figure must never appear.");
idx.push("- Batteries are framed as the wrong tool for heating, not as the enemy: \"one system instead of two\".");
idx.push("- No em dashes, and no en dashes in ranges: write \"3 to 5 years\". Straight quotes. Contractions welcome. Australian spelling.");
idx.push("");
idx.push("## Pages");
const used = new Set();
for (const [name, test] of SECTIONS) {
  const rows = pages.filter((p) => !used.has(p.rel) && test(p.rel));
  rows.forEach((p) => used.add(p.rel));
  if (!rows.length) continue;
  idx.push("");
  idx.push(`### ${name}`);
  idx.push("");
  idx.push("| page | words | flags |");
  idx.push("|---|---|---|");
  for (const p of rows) {
    const w = p.blocks.reduce((a, b) => a + b.text.split(/\s+/).length, 0);
    const fl = p.blocks.flatMap((b) => b.flags).filter((x) => x !== "CTA");
    idx.push(`| [${p.rel}](pages/${slug(p.rel)}.md) | ${w} | ${fl.length ? fl.join(", ") : ""} |`);
  }
}
idx.push("");
idx.push("## Mechanical flags across the site");
idx.push("");
idx.push(`- em dashes (banned): ${emDashLines.length}${emDashLines.length ? " -> " + emDashLines.join(", ") : ""}`);
idx.push(`- draft figures awaiting sign-off: ${draftLines.length}${draftLines.length ? " -> " + draftLines.join(", ") : ""}`);
idx.push(`- curly quotes: ${curlyLines.length}${curlyLines.length ? " -> " + curlyLines.join(", ") : ""}`);
idx.push(`- en dashes (ranges should read "to"): ${enDashLines.length}${enDashLines.length ? " -> " + enDashLines.join(", ") : ""}`);
fs.writeFileSync(path.join(PACK, "INDEX.md"), idx.join("\n") + "\n", "utf8");
console.log(`Wrote .claude/copy-review/ (INDEX.md + ${pages.length} page files) for human reviewers.`);
