/* Extracts every page's customer-facing copy into one reviewable file.

     npm run copy:dump

   Why: copy lives inside 28 hand-written HTML files and only ~38% of those
   bytes are words. A review session that reads the raw pages spends most of
   its context on markup. This writes a single file of just the copy, with a
   `path:line` on every block so any finding maps straight back to the edit.

   Output goes to .claude/copy-dump.txt, which is gitignored and excluded from
   the deploy. Do NOT write it to the repo root: this is a static site served
   from the root, so a file there is publicly fetchable.

   This prints only a summary. Read the output file for the copy itself. */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, ".claude", "copy-dump.txt");

/* Generated or non-copy trees. assets/animations is generated by
   build-homepage-anim.js, so its strings are reviewed at the source, not here. */
const SKIP_DIRS = new Set(["node_modules", ".git", ".claude", "tools", "scripts"]);
const SKIP_PATHS = [path.join("assets", "animations")];

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".") && entry.name !== ".claude") continue;
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.relative(ROOT, full);
    if (SKIP_PATHS.some((p) => rel.startsWith(p))) continue;
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith(".html")) out.push(full);
  }
  return out;
}

const ENTITIES = {
  amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ",
  mdash: "—", ndash: "–", hellip: "...", times: "×",
  harr: "<->", rarr: "->", larr: "<-", deg: "°", sup2: "²",
  copy: "©", reg: "®", trade: "™", middot: "·",
};

function decode(s) {
  return s
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&([a-z][a-z0-9]*);/gi, (m, name) => {
      const k = name.toLowerCase();
      return Object.prototype.hasOwnProperty.call(ENTITIES, k) ? ENTITIES[k] : m;
    });
}

const stripTags = (s) => s.replace(/<[^>]*>/g, " ");
/* Inline tags (<strong>, <a>) become spaces, which strands punctuation:
   "$40,000 ." and "thermal store : an". Pull it back after collapsing. */
const tidy = (s) =>
  decode(stripTags(s))
    .replace(/\s+/g, " ")
    .replace(/\s+([,.;:!?%])/g, "$1")
    .replace(/\(\s+/g, "(")
    .replace(/\s+\)/g, ")")
    .trim();
const hasWords = (s) => /[a-z]{2}/i.test(s);

/* The quote char has to be captured and back-referenced: several descriptions
   are double-quoted but contain an apostrophe, and a [^"']* class truncates
   them at "customer's". */
function attr(html, re) {
  const m = html.match(re);
  if (!m) return null;
  return decode(m[m.length - 1]).trim();
}

const CURLY = /[‘’“”]/;

const files = walk(ROOT).sort();
const pages = [];
let emDashLines = [];
let draftLines = [];
let curlyLines = [];

for (const file of files) {
  const rel = path.relative(ROOT, file).replace(/\\/g, "/");
  const src = fs.readFileSync(file, "utf8");
  const lines = src.split(/\r?\n/);

  const page = {
    rel,
    title: attr(src, /<title>([^<]*)<\/title>/i),
    description: attr(src, /<meta\s+name=(["'])description\1\s+content=(["'])([\s\S]*?)\2/i),
    ogTitle: attr(src, /<meta\s+property=(["'])og:title\1\s+content=(["'])([\s\S]*?)\2/i),
    blocks: [],
    chartLabels: [],
  };

  let inBody = false;
  let skipUntil = null; // closing tag we're waiting for (script/style)
  let svgDepth = 0;

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const n = i + 1;

    if (!inBody) {
      if (/<body[\s>]/i.test(raw)) inBody = true;
      continue;
    }
    if (/<\/body>/i.test(raw)) break;

    if (skipUntil) {
      if (new RegExp(`</${skipUntil}`, "i").test(raw)) skipUntil = null;
      continue;
    }
    const opens = raw.match(/<(script|style)[\s>]/i);
    if (opens && !new RegExp(`</${opens[1]}`, "i").test(raw)) {
      skipUntil = opens[1].toLowerCase();
      continue;
    }

    /* SVG: the tags are markup but <text> holds real chart labels, and the
       draft figures live in them. Collect those separately. */
    const svgOpen = (raw.match(/<svg[\s>]/gi) || []).length;
    const svgClose = (raw.match(/<\/svg>/gi) || []).length;
    if (svgDepth > 0 || svgOpen > 0) {
      const texts = raw.match(/<text[^>]*>([^<]*)<\/text>/gi) || [];
      for (const t of texts) {
        const v = tidy(t);
        if (v) page.chartLabels.push({ n, text: v });
      }
      svgDepth += svgOpen - svgClose;
      if (svgDepth < 0) svgDepth = 0;
      if (svgOpen > 0 || svgDepth > 0) continue;
    }

    const text = tidy(raw);
    if (!text || !hasWords(text)) continue;

    const flags = [];
    if (/class="[^"]*\bdraft\b/.test(raw)) { flags.push("DRAFT"); draftLines.push(`${rel}:${n}`); }
    if (/<button|class="btn\b|class="[^"]*\bbtn\b/.test(raw)) flags.push("CTA");
    if (text.includes("—")) { flags.push("EM-DASH"); emDashLines.push(`${rel}:${n}`); }
    if (CURLY.test(text)) { flags.push("CURLY-QUOTE"); curlyLines.push(`${rel}:${n}`); }

    page.blocks.push({ n, text, flags });
  }

  pages.push(page);
}

/* ---------- write the dump ---------- */
const out = [];
out.push("THERMAL DAWN, SITE COPY DUMP");
out.push("Generated by npm run copy:dump. Do not edit this file; edit the pages.");
out.push("Every block is prefixed with the file and line it came from.");
out.push("Flags: [DRAFT] figure awaiting sign-off, [CTA] button label,");
out.push("       [EM-DASH] banned punctuation, [CURLY-QUOTE] smart quote where the site uses straight.");
out.push("");
out.push(`${pages.length} pages.`);
out.push("=".repeat(78));

for (const p of pages) {
  out.push("");
  out.push(`## ${p.rel}`);
  if (p.title) out.push(`   <title>       ${p.title}`);
  if (p.ogTitle && p.ogTitle !== p.title) out.push(`   og:title      ${p.ogTitle}`);
  if (p.description) out.push(`   description   ${p.description}`);
  out.push("");
  for (const b of p.blocks) {
    const flag = b.flags.length ? ` [${b.flags.join("][")}]` : "";
    out.push(`${String(b.n).padStart(4)}:${flag} ${b.text}`);
  }
  if (p.chartLabels.length) {
    out.push("");
    out.push("   -- chart labels (inside SVG) --");
    for (const c of p.chartLabels) out.push(`${String(c.n).padStart(4)}:  ${c.text}`);
  }
}

out.push("");
out.push("=".repeat(78));
out.push("MECHANICAL FLAGS");
out.push(`em dashes (banned sitewide): ${emDashLines.length}${emDashLines.length ? " -> " + emDashLines.join(", ") : ""}`);
out.push(`draft figures awaiting sign-off: ${draftLines.length}${draftLines.length ? " -> " + draftLines.join(", ") : ""}`);
out.push(`curly quotes (site uses straight): ${curlyLines.length}${curlyLines.length ? " -> " + curlyLines.join(", ") : ""}`);

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out.join("\n") + "\n", "utf8");

const words = pages.reduce((a, p) => a + p.blocks.reduce((b, x) => b + x.text.split(/\s+/).length, 0), 0);
const bytes = fs.statSync(OUT).size;
console.log(`Wrote ${path.relative(ROOT, OUT).replace(/\\/g, "/")}`);
console.log(`  ${pages.length} pages, ${words.toLocaleString()} words, ${(bytes / 1024).toFixed(0)} KB (~${Math.round(bytes / 4).toLocaleString()} tokens)`);
console.log(`  em dashes: ${emDashLines.length}, draft figures: ${draftLines.length}, curly quotes: ${curlyLines.length}`);
console.log(`Read that file to review the copy. Report findings as path:line.`);
