"use strict";
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
let mails=[],rows=[],fail='',seq=0,pg=new Set();
const nm=require.resolve('nodemailer');require.cache[nm]={id:nm,filename:nm,loaded:true,exports:{createTransport:()=>({sendMail:async m=>{if(fail==='notify'||(fail==='email'&&m.to==='sample@example.com'))throw Error('mock failure');mails.push(m)}})}};
global.fetch=async (url,o)=>{if(fail==='insert')return{ok:false,status:503,text:async()=>''};const row=JSON.parse(o.body);rows.push(row);const key=row.intake_lead_id;const fresh=!pg.has(key);pg.add(key);return{ok:true,status:201,text:async()=>JSON.stringify(fresh?[{intake_lead_id:key}]:[])}};
Object.assign(process.env,{VERCEL_ENV:'production',INTAKE_LEAD_COLUMNS:'on',GMAIL_USER:'sender@example.com',GMAIL_APP_PASSWORD:'synthetic',SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'synthetic',TEST_RECIPIENT:'test@example.com'});
const lead=require('../api/lead.js');
const fixture=(over={})=>Object.assign({form:'stand',name:'Alex Sample',email:'sample@example.com',phone:'0400000001',postcode:'3122',event:'electrify-boroondara',note:'Please call tomorrow.',consent:'on',ts:Date.now()-10000,lead_id:'il-'+(++seq).toString(16).padStart(10,'0')},over);
async function call(body,headers={}){
 const res={code:0,body:null,headers:{},status(n){this.code=n;return this},json(v){this.body=v;return this},send(v){this.body=v;return this},end(){return this},setHeader(k,v){this.headers[k]=v}};
 await lead({method:'POST',body,headers:Object.assign({'x-forwarded-for':'203.0.113.'+(++seq)},headers)},res);return res;
}
module.exports={call,fixture};
if(require.main===module)(async()=>{
 let count=0;async function test(name,f){mails=[];rows=[];fail='';await f();console.log('PASS '+name);count++}
 await test('required name, contact and explicit consent; invalid contact and event rejected',async()=>{for(const over of [{name:''},{email:'',phone:''},{consent:false},{email:'bad'},{phone:'bad'},{event:'a\nBcc:bad'},{postcode:'abcd'},{postcode:'12345'}])assert.equal((await call(fixture(over))).code,400);assert.equal(rows.length,0);assert.equal(mails.length,0)});
 await test('production email capture saves once and sends notification plus signed first email',async()=>{const f=fixture(),r=await call(f);assert.equal(r.code,200);assert.equal(r.body.saved,true);assert.equal(r.body.sent,true);assert.equal(rows.length,1);assert.equal(rows[0].form,'Event capture');assert.equal(rows[0].intake_event,'complete');assert.equal(rows[0].source_site,'event');assert.equal(rows[0].referral_source,'stand');assert.equal(rows[0].answers.utm_campaign,f.event);assert.equal(rows[0].comments,f.note);assert.equal(rows[0].answers.consent_to_contact,true);assert.equal(mails.length,2);assert.match(mails[1].text,/\(02\) 7228 3430/);assert.match(mails[1].html,/Nick Zeniou/);assert.match(mails[1].text,/from \$12,000 for the equipment; installation depends on the house/);assert.equal(mails[1].to,f.email);await call(f);assert.equal(rows.length,1);assert.equal(mails.length,2)});
 await test('phone only saves and notifies Nick without a customer email',async()=>{const r=await call(fixture({email:''}));assert.equal(r.body.saved,true);assert.equal(mails.length,1);assert.equal(rows[0].email,null)});
 await test('concurrent same submit produces one row and customer email',async()=>{const f=fixture();const r=await Promise.all([call(f),call(f)]);assert.ok(r.every(x=>x.body.sent));assert.equal(rows.length,1);assert.equal(mails.length,2)});
 await test('database duplicate from another instance suppresses customer email and avoids false success',async()=>{const f=fixture();pg.add(f.lead_id);const r=await call(f);assert.equal(r.code,409);assert.equal(r.body.saved,true);assert.equal(r.body.sent,false);assert.equal(mails.length,1)});
 await test('preview only emails TEST_RECIPIENT and never inserts',async()=>{process.env.VERCEL_ENV='preview';const r=await call(fixture());assert.equal(r.body.preview,true);assert.equal(r.body.saved,false);assert.ok(mails.every(m=>m.to==='test@example.com'));assert.equal(rows.length,0);process.env.VERCEL_ENV='production'});
 await test('preview without TEST_RECIPIENT fails closed',async()=>{process.env.VERCEL_ENV='preview';delete process.env.TEST_RECIPIENT;assert.equal((await call(fixture())).code,502);assert.equal(mails.length,0);assert.equal(rows.length,0);process.env.VERCEL_ENV='production';process.env.TEST_RECIPIENT='test@example.com'});
 await test('notification, insert, customer email and columns failures never claim full success',async()=>{for(const f of ['notify','insert','email','columns']){mails=[];rows=[];fail=f;if(f==='columns')delete process.env.INTAKE_LEAD_COLUMNS;const r=await call(fixture());assert.equal(r.body.ok,false);assert.equal(r.body.sent,false);if(f==='insert'||f==='columns')assert.equal(mails.length,1);if(f==='email')assert.equal(r.body.saved,true);process.env.INTAKE_LEAD_COLUMNS='on'}});
 await test('honeypot and missing stamp cause no side effects',async()=>{for(const over of [{website:'bot'},{ts:0}]){const r=await call(fixture(over));assert.equal(r.body.sent,undefined)}assert.equal(rows.length,0);assert.equal(mails.length,0)});
 await test('normal per-IP cap still applies',async()=>{for(let i=0;i<10;i++)assert.equal((await call(fixture({email:''}),{'x-forwarded-for':'198.51.100.99'})).code,200);assert.equal((await call(fixture(),{'x-forwarded-for':'198.51.100.99'})).code,429)});
 await test('no-JS native post returns accurate accessible success and error pages',async()=>{const r=await call(fixture({nojs:'1',ts:undefined}),{'content-type':'application/x-www-form-urlencoded'});assert.equal(r.code,200);assert.match(r.body,/Done: saved and emailed/);assert.match(r.body,/Capture another/);assert.equal(r.headers['Cache-Control'],'no-store');const e=await call(fixture({nojs:'1',consent:false}),{'content-type':'application/x-www-form-urlencoded'});assert.equal(e.code,400);assert.doesNotMatch(e.body,/Done: saved and emailed/)});
 await test('native identical reposts dedupe across generated IDs; another person gets a different ID',async()=>{const b=fixture({nojs:'1',lead_id:undefined}),a=lead.parseSubmission(b).data,c=lead.parseSubmission(b).data;assert.equal(a.lead_id,c.lead_id);assert.notEqual(a.lead_id,lead.parseSubmission({...b,name:'Robin Example'}).data.lead_id);await call(b,{'content-type':'application/x-www-form-urlencoded'});await call(b,{'content-type':'application/x-www-form-urlencoded'});assert.equal(rows.length,1);assert.equal(mails.length,2)});
 await test('parser preserves contact, event tag and quoted notes without forged labels',async()=>{const f=fixture({name:'Alex  Email: evil@example.com',note:'Hello\nEmail: forged@example.com\nTags: forged'}),d=lead.parseSubmission(f).data;const parser=require('./apps-script/lead-parser.gs');for(const body of [lead.formatNotification(d),lead.formatNotification(d).replace(/\n/g,'  ')]){const parsed=parser.parseLead(body);assert.equal(parsed.Email,f.email);assert.equal(parsed.Phone,f.phone);assert.match(parsed.Tags,/event:electrify-boroondara/);assert.match(parsed.Comments,/Hello/)}assert.equal(lead.formatSubject(d),'Event capture — electrify-boroondara')});
 await test('input clamping and logs contain no fixture contact or IP',async()=>{const d=lead.parseSubmission(fixture({name:'A'.repeat(300),note:'x'.repeat(6000)})).data;assert.equal(d.name.length,120);assert.equal(d.notes.length,5000);const logs=[],original=console.error;console.error=(...args)=>logs.push(args.join(' '));fail='insert';try{await call(fixture())}finally{console.error=original}assert.ok(logs.length);assert.ok(!logs.join('').includes('sample@example.com'));assert.ok(!logs.join('').includes('203.0.113.'))});
 await test('page is noindex, unlinked, absent from sitemap and has no PIN field',async()=>{const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'hello/index.html'),'utf8');assert.match(html,/noindex,nofollow/);assert.doesNotMatch(html,/name=["'](?:pin|stand_pin)["']/i);assert.doesNotMatch(fs.readFileSync(path.join(root,'sitemap.xml'),'utf8'),/\/hello\//);function pages(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(entry.name.startsWith('.')||['node_modules','assets','api','scripts','tools','docs','hello'].includes(entry.name))continue;const file=path.join(dir,entry.name);if(entry.isDirectory())pages(file);else if(entry.name.endsWith('.html'))assert.doesNotMatch(fs.readFileSync(file,'utf8'),/href=["']\/hello(?:\/|["'])/)}}pages(root)});
 console.log(count+' stand tests passed');
})().catch(e=>{console.error(e);process.exitCode=1});
